//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPhysioThrapy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dTharapyDBEntities : DbContext
    {
        public dTharapyDBEntities()
            : base("name=dTharapyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Messages> tbl_Messages { get; set; }
        public DbSet<tbl_Patients> tbl_Patients { get; set; }
        public DbSet<tbl_trainers> tbl_trainers { get; set; }
    }
}
