//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPhysioThrapy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_trainers
    {
        public int id { get; set; }
        public string t_Name { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
    }
}
