//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalPhysioThrapy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Messages
    {
        public int id { get; set; }
        public string message { get; set; }
        public Nullable<int> PatientsIDFK { get; set; }
        public Nullable<bool> IsVideo { get; set; }
    }
}
